### ISSUE TITLE
Ability to add custom meetups using a slack command

### ISSUE THREAD

**Issue by san650** [marpo60/meetup_bot#23]
Synopsis

```
/meetup add 2024-08-17 'Photography Meetup' https://wwww.example.com/photography-meetup/2024-08-17
```

Then the meetup will be merged with the information gathered from meetup.com. This would require an internal database that could be pruned for old meetups.

We could limit what people can use this command if we see this as potential spam, another way is to store what person added the event.

**Comment by marpo60** [comment]
Fixed https://github.com/marpo60/meetup_bot/pull/65

The way for adding a custom meetup is through a PR in [this file](https://github.com/marpo60/meetup_bot/blob/main/lib/meetup_bot/workers/sync_manual_events_worker.ex#L22-L34)
